### Importing Important libraries

In [1]:
import pandas as pd

### Loading the dataset

In [2]:
data = pd.read_csv('/Users/deepikakala/Documents/Projects/Medicine Suggestion System/dataset/training.csv')

In [3]:
data.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [4]:
data.shape

(4920, 133)

### Splitting the dataset

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X=data.iloc[:,:-1]
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [7]:
Y=data.iloc[:,-1]

In [8]:
print(Y)

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object


Column Encoding

In [9]:
import numpy as np

In [10]:
from sklearn.preprocessing import LabelEncoder

# Create a label encoder
le = LabelEncoder()

# Fit and transform the labels in Y
Y_encoded = le.fit_transform(Y)

# Now split the dataset
x_train, x_test, y_train, y_test = train_test_split(X, Y_encoded, random_state=0, test_size=0.2)

# Check the unique classes after encoding
print("Unique classes in y_train after encoding:", np.unique(y_train))

Unique classes in y_train after encoding: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [11]:
print(x_train.shape)

(3936, 132)


In [12]:
print(y_train.shape)

(3936,)


In [13]:
print(x_test.shape)

(984, 132)


In [14]:
print(y_test.shape)

(984,)


### MOdel Selction

In [15]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

Model Training 

In [16]:
models = {
    "Random Forest Classifier": RandomForestClassifier(n_estimators=100, random_state=42),
    "Gradient Boosting Classifier" : GradientBoostingClassifier(n_estimators=100, random_state=42),
    "Logistic Regression" : LogisticRegression(),
    "Support Vector Machine" : SVC(kernel='linear'),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "K-Nearest Neighbour" : KNeighborsClassifier(n_neighbors=5),
    "MultiNomial NB" : MultinomialNB()
    
}

In [17]:
for model_name, model in models.items():
    print(model_name , ':' , model)
    model.fit(x_train, y_train)
    prediction = model.predict(x_test)
    accuracy = accuracy_score(y_test, prediction)
    conf_matrix = confusion_matrix(y_test, prediction)

    print(f"Model Name is : {model_name} & Accuracy is :  {accuracy}\n")
    print(f"Model Name is : {model_name} & Confusion matrix is \n  {conf_matrix}")
    print(np.array2string(conf_matrix, separator=','))


Random Forest Classifier : RandomForestClassifier(random_state=42)
Model Name is : Random Forest Classifier & Accuracy is :  1.0

Model Name is : Random Forest Classifier & Confusion matrix is 
  [[18  0  0 ...  0  0  0]
 [ 0 22  0 ...  0  0  0]
 [ 0  0 31 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 24]]
[[18, 0, 0,..., 0, 0, 0],
 [ 0,22, 0,..., 0, 0, 0],
 [ 0, 0,31,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,20, 0, 0],
 [ 0, 0, 0,..., 0,28, 0],
 [ 0, 0, 0,..., 0, 0,24]]
Gradient Boosting Classifier : GradientBoostingClassifier(random_state=42)
Model Name is : Gradient Boosting Classifier & Accuracy is :  1.0

Model Name is : Gradient Boosting Classifier & Confusion matrix is 
  [[18  0  0 ...  0  0  0]
 [ 0 22  0 ...  0  0  0]
 [ 0  0 31 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 24]]
[[18, 0, 0,..., 0, 0, 0],
 [ 0,22, 0,..., 0, 0, 0],
 [ 0, 0,31,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,20, 0, 0],
 [ 0, 0,

Train THe Model

In [18]:
# selecting svc
svc = SVC(kernel='linear')
svc.fit(x_train,y_train)
ypred = svc.predict(x_test)
accuracy_score(y_test,ypred)

1.0

Save the MODel

In [19]:
import pickle
svc = pickle.load(open("/Users/deepikakala/Documents/Projects/Medicine Suggestion System/models/svc.pkl", 'rb'))

In [20]:
x_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
1525        0          0                     0                    0   
1013        0          0                     0                    0   
1892        0          0                     0                    0   
1972        0          0                     0                    0   
873         0          0                     0                    0   
...       ...        ...                   ...                  ...   
3871        0          1                     0                    0   
1366        0          0                     0                    0   
854         1          0                     0                    0   
4224        0          0                     0                    1   
452         1          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
1525          0       0           0             0        0                 0   
1013          0       0           1             0        0                 0   
1892          0       0           0             0        0                 0   
1972          0       0           0             0        0                 0   
873           0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
3871          0       1           1             0        0                 0   
1366          0       0           0             0        0                 0   
854           0       0           0             0        0                 0   
4224          1       1           0             0        0                 0   
452           0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
1525  ...                   0           0         0             0   
1013  ...                   0           0         0             0   
1892  ...                   0           0         0             0   
1972  ...                   0           0         0             0   
873   ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
3871  ...                   0           0         0             0   
1366  ...                   0           0         0             0   
854   ...                   0           0         0             0   
4224  ...                   0           0         0             0   
452   ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
1525                    0                     0                   0        0   
1013                    0                     0                   0        0   
1892                    0                     0                   0        0   
1972                    0                     0                   0        0   
873                     0                     0                   0        0   
...                   ...                   ...                 ...      ...   
3871                    0                     0                   0        0   
1366                    0                     0                   0        0   
854                     0                     0                   0        0   
4224                    0                     0                   0        0   
452                     0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
1525                     0                  0  
1013                     0                  0  
1892                     0                  0  
1972                     0                  0  
873                      0                  0  
...                    ...                ...  
3871                     0                  0  
1366              

In [21]:
x_test.iloc[0].values.reshape(1, -1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
print("Model Predicted Disease: ", svc.predict(x_test.iloc[0].values.reshape(1, -1)))

Model Predicted Disease:  ['Heart attack']


/Users/deepikakala/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [23]:
print("Model Actual Disease: ", y_test[0])

Model Actual Disease:  18


In [24]:
print("predicted disease :",svc.predict(x_test.iloc[0].values.reshape(1,-1)))
print("Actual Disease :", y_test[0])

predicted disease : ['Heart attack']
Actual Disease : 18


/Users/deepikakala/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [25]:
# print(y_test.index)

Recommendation System and Prediction

LOad DB and Use Logic for recommendations

In [26]:
sys_des = pd.read_csv('/Users/deepikakala/Documents/Projects/Medicine Suggestion System/dataset/symtoms_df.csv')

In [27]:
sys_des.shape

(4920, 6)

In [28]:
sys_des.head()

Unnamed: 0           Disease   Symptom_1              Symptom_2  \
0           0  Fungal infection     itching              skin_rash   
1           1  Fungal infection   skin_rash   nodal_skin_eruptions   
2           2  Fungal infection     itching   nodal_skin_eruptions   
3           3  Fungal infection     itching              skin_rash   
4           4  Fungal infection     itching              skin_rash   

               Symptom_3             Symptom_4  
0   nodal_skin_eruptions   dischromic _patches  
1    dischromic _patches                   NaN  
2    dischromic _patches                   NaN  
3    dischromic _patches                   NaN  
4   nodal_skin_eruptions                   NaN

In [29]:
precautions = pd.read_csv('/Users/deepikakala/Documents/Projects/Medicine Suggestion System/dataset/precautions_df.csv')

In [30]:
precautions.head()

Unnamed: 0         Disease                      Precaution_1  \
0           0   Drug Reaction                   stop irritation   
1           1         Malaria          Consult nearest hospital   
2           2         Allergy                    apply calamine   
3           3  Hypothyroidism                     reduce stress   
4           4       Psoriasis  wash hands with warm soapy water   

                   Precaution_2        Precaution_3  \
0      consult nearest hospital    stop taking drug   
1               avoid oily food  avoid non veg food   
2       cover area with bandage                 NaN   
3                      exercise         eat healthy   
4  stop bleeding using pressure      consult doctor   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths

In [31]:
workout = pd.read_csv('/Users/deepikakala/Documents/Projects/Medicine Suggestion System/dataset/workout_df.csv')

In [32]:
workout.head()

Unnamed: 0.1  Unnamed: 0           Disease                    workout
0             0           0  Fungal infection         Avoid sugary foods
1             1           1  Fungal infection         Consume probiotics
2             2           2  Fungal infection  Increase intake of garlic
3             3           3  Fungal infection     Include yogurt in diet
4             4           4  Fungal infection      Limit processed foods

In [33]:
description = pd.read_csv('/Users/deepikakala/Documents/Projects/Medicine Suggestion System/dataset/description.csv')

In [34]:
description.head()

Disease                                        Description
0     Fungal infection  Fungal infection is a common skin condition ca...
1              Allergy  Allergy is an immune system reaction to a subs...
2                 GERD  GERD (Gastroesophageal Reflux Disease) is a di...
3  Chronic cholestasis  Chronic cholestasis is a condition where bile ...
4        Drug Reaction  Drug Reaction occurs when the body reacts adve...

In [35]:
medication = pd.read_csv('/Users/deepikakala/Documents/Projects/Medicine Suggestion System/dataset/medications.csv')

In [36]:
medication.head()

Disease                                         Medication
0     Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1              Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...
2                 GERD  ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...
3  Chronic cholestasis  ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...
4        Drug Reaction  ['Antihistamines', 'Epinephrine', 'Corticoster...

In [37]:
diet = pd.read_csv('/Users/deepikakala/Documents/Projects/Medicine Suggestion System/dataset/diets.csv')

In [38]:
diet.head()

Disease                                               Diet
0     Fungal infection  ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...
1              Allergy  ['Elimination Diet', 'Omega-3-rich foods', 'Vi...
2                 GERD  ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...
3  Chronic cholestasis  ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...
4        Drug Reaction  ['Antihistamine Diet', 'Omega-3-rich foods', '...

In [39]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}


In [40]:
def get_predicted_value(patient_symptoms):
    # Check for invalid symptoms
    invalid_symptoms = [symptom for symptom in patient_symptoms if symptom not in symptoms_dict]
    if invalid_symptoms:
        return f"Invalid symptoms detected: {', '.join(invalid_symptoms)}. Please check your input."


    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    predicted_index = svc.predict([input_vector])[0]
    print(f"Predicted index: {predicted_index}")
    return diseases_list.get(predicted_index, predicted_index)


In [41]:
def helper(dis):
    desc = description[description['Disease'] == predicted_disease]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medication[medication['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diet[diet['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['Disease'] == dis] ['workout']


    return desc,pre,med,die,wrkout


In [42]:
# Test 1
# Split the user's input into a list of symptoms (assuming they are comma-separated) # itching,skin_rash,nodal_skin_eruptions
symptoms = input("Enter your symptoms.......")
user_symptoms = [s.strip() for s in symptoms.split(',')]
# Remove any extra characters, if any
user_symptoms = [symptom.strip("[]' ") for symptom in user_symptoms]

chest_pain, cough, stomach_pain, acidity, ulcers_on_tongue

In [43]:
print(user_symptoms)

['chest_pain', 'cough', 'stomach_pain', 'acidity', 'ulcers_on_tongue']


In [44]:
predicted_disease = get_predicted_value(user_symptoms)

Predicted index: GERD


/Users/deepikakala/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [45]:
print(predicted_disease)

GERD


Description

In [46]:
description.head()

Disease                                        Description
0     Fungal infection  Fungal infection is a common skin condition ca...
1              Allergy  Allergy is an immune system reaction to a subs...
2                 GERD  GERD (Gastroesophageal Reflux Disease) is a di...
3  Chronic cholestasis  Chronic cholestasis is a condition where bile ...
4        Drug Reaction  Drug Reaction occurs when the body reacts adve...

In [47]:
# Get the corresponding description
descriptions = description.loc[description['Disease'] == predicted_disease, 'Description']

# Check if the description exists
if not descriptions.empty:
    print(f"Description for '{predicted_disease}': {descriptions.values[0]}")
else:
    print(f"No description found for '{predicted_disease}'.")

Description for 'GERD': GERD (Gastroesophageal Reflux Disease) is a digestive disorder that affects the lower esophageal sphincter.


Precautions

In [48]:
precautions.head()

Unnamed: 0         Disease                      Precaution_1  \
0           0   Drug Reaction                   stop irritation   
1           1         Malaria          Consult nearest hospital   
2           2         Allergy                    apply calamine   
3           3  Hypothyroidism                     reduce stress   
4           4       Psoriasis  wash hands with warm soapy water   

                   Precaution_2        Precaution_3  \
0      consult nearest hospital    stop taking drug   
1               avoid oily food  avoid non veg food   
2       cover area with bandage                 NaN   
3                      exercise         eat healthy   
4  stop bleeding using pressure      consult doctor   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths

In [49]:
# Get all precautions for the predicted disease
precaution_rows = precautions.loc[precautions['Disease'] == predicted_disease]

# Check if any precautions exist for the predicted disease
if not precaution_rows.empty:
    # Dynamically select all precaution columns
    precaution_columns = [col for col in precautions.columns if col.startswith('Precaution')]
    
    # Extract precautions from the relevant columns
    precautions_list = precaution_rows[precaution_columns].values.flatten()
    
    # Filter out any None or empty values
    precautions_list = [precaution for precaution in precautions_list if pd.notna(precaution) and precaution != '']
    
    if precautions_list:
        print(f"Precautions for '{predicted_disease}': \n {', '.join(precautions_list)}")
        
    else:
        print(f"No precautions found for '{predicted_disease}'.")
else:
    print(f"No record found for '{predicted_disease}'.")

Precautions for 'GERD': 
 avoid fatty spicy food, avoid lying down after eating, maintain healthy weight, exercise


Medications

In [50]:
medication.head()

Disease                                         Medication
0     Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1              Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...
2                 GERD  ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...
3  Chronic cholestasis  ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...
4        Drug Reaction  ['Antihistamines', 'Epinephrine', 'Corticoster...

In [51]:
# Get the corresponding description
medications = medication.loc[medication['Disease'] == predicted_disease, 'Medication']

# Check if the description exists
if not medications.empty:
    print(f"Medication for '{predicted_disease}':\n {medications.values[0]}")
else:
    print(f"No medication found for '{predicted_disease}'.")

Medication for 'GERD':
 ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers', 'Antacids', 'Prokinetics', 'Antibiotics']


Diets

In [52]:
# Get the corresponding description
diets = diet.loc[diet['Disease'] == predicted_disease, 'Diet']

# Check if the description exists
if not diets.empty:
    print(f"Diets for '{predicted_disease}':\n {diets.values[0]}")
else:
    print(f"No Diets found for '{predicted_disease}'.")

Diets for 'GERD':
 ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger', 'Licorice', 'Aloe vera juice']


Workout

In [53]:
# Get the corresponding description
workouts = workout.loc[workout['Disease'] == predicted_disease, 'workout']

# Check if the description exists
if not workouts.empty:
    print(f"Workout for '{predicted_disease}':\n {workouts.values[0]}")
else:
    print(f"No Workout found for '{predicted_disease}'.")

Workout for 'GERD':
 Consume smaller meals


In [54]:
desc, pre, med, die, wrkout = helper(predicted_disease)

In [55]:
from datetime import date


In [56]:
def patients_prescription(patient_symptoms):
    name = input("Enter Your Name: ")
    print(f"Your Name: {name}")
    age = input("Enter Your Age: ")
    print(f"Your Name: {age}")
    today = date.today()
    print(f"Date of Treatment: {today}")
    def format_symptoms(symptoms):
        return [symptom.replace('_', ' ').capitalize() for symptom in symptoms]

    formatted_symptoms = format_symptoms(user_symptoms)
    print("Symptoms:")
    for index, symptom in enumerate(formatted_symptoms, start=1):
        print(f" {index}. {symptom}")
    print(f"You have disease named {predicted_disease}\n")
    print(f"=================================================Get the Description {predicted_disease}================================================\n")
    # Get the corresponding description
    descriptions = description.loc[description['Disease'] == predicted_disease, 'Description']

    # Check if the description exists
    if not descriptions.empty:
        print(f"Description for '{predicted_disease}':\n {descriptions.values[0]}\n")
    else:
        print(f"No description found for '{predicted_disease}'.")

    print(f"==================================================Get the Precaution {predicted_disease}================================================\n")
    # Get all precautions for the predicted disease

    
    precaution_rows = precautions.loc[precautions['Disease'] == predicted_disease]

    # Check if any precautions exist for the predicted disease
    if precautions_list:
        print(f"Precautions for '{predicted_disease}':")
        for index, precaution in enumerate(precautions_list, start=1):
            print(f"{index}. {precaution}")  # Print index and precaution on separate lines
            print()  # Add an extra newline for spacing
    else:
        print(f"No precautions found for '{predicted_disease}'.")


    print(f"=================================================Get the Medication {predicted_disease}=================================================\n")
    # Get the corresponding description
    medications = medication.loc[medication['Disease'] == predicted_disease, 'Medication']

    # Check if the description exists
    if not medications.empty:
        print(f"Medication for '{predicted_disease}':\n {medications.values[0]}\n")
    else:
        print(f"No medication found for '{predicted_disease}'.")

    print(f"==================================================Get the Diet {predicted_disease}======================================================\n")
    # Get the corresponding description
    diets = diet.loc[diet['Disease'] == predicted_disease, 'Diet']

    # Check if the description exists
    if not diets.empty:
        print(f"Diets for '{predicted_disease}':\n {diets.values[0]}\n")
    else:
        print(f"No Diets found for '{predicted_disease}'.\n")

    print(f"==================================================Get the Workout {predicted_disease}===================================================\n")

    # Get the corresponding description
    workouts = workout.loc[workout['Disease'] == predicted_disease, 'workout']

    # Check if the description exists
    if not workouts.empty:
        print(f"Workout for '{predicted_disease}':\n {workouts.values[0]}\n")
    else:
        print(f"No Workout found for '{predicted_disease}'.\n")

    print(f"=========================================================================================================================\n")


In [57]:
patients_prescription(predicted_disease)

Your Name: Deepika
Your Name: 26
Date of Treatment: 2024-11-23
Symptoms:
 1. Chest pain
 2. Cough
 3. Stomach pain
 4. Acidity
 5. Ulcers on tongue
You have disease named GERD

=================================================Get the Description GERD================================================

Description for 'GERD':
 GERD (Gastroesophageal Reflux Disease) is a digestive disorder that affects the lower esophageal sphincter.

==================================================Get the Precaution GERD================================================

Precautions for 'GERD':
1. avoid fatty spicy food

2. avoid lying down after eating

3. maintain healthy weight

4. exercise

=================================================Get the Medication GERD=================================================

Medication for 'GERD':
 ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers', 'Antacids', 'Prokinetics', 'Antibiotics']

==================================================Get the Diet GERD===========